---
- name: Label node for Kata support
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ ansible_hostname }}"
        labels:
          katacontainers.io/kata-runtime: "true"

- name: Create kata-fc RuntimeClass
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: node.k8s.io/v1
      kind: RuntimeClass
      metadata:
        name: kata-fc
      handler: kata-fc
      overhead:
        podFixed:
          memory: "160Mi"
          cpu: "250m"

- name: Create kata-qemu RuntimeClass
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: node.k8s.io/v1
      kind: RuntimeClass
      metadata:
        name: kata-qemu
      handler: kata-qemu
      overhead:
        podFixed:
          memory: "160Mi"
          cpu: "250m"
