version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /services/control-plane
    schedule:
      interval: weekly

  - package-ecosystem: swift
    directory: /clients/ios
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
