---
kata_version: "3.24.0"
kata_install_dir: "/opt/kata"
kata_bin_dir: "/usr/local/bin"
kata_config_dir: "/etc/kata-containers"

# Containerd configuration (k3s uses template)
kata_containerd_config_dir: "/var/lib/rancher/k3s/agent/etc/containerd"
kata_devmapper_pool_name: "containerd-pool"
kata_devmapper_base_image_size: "10GB"
