---
collections:
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
  - name: kubernetes.core
    version: ">=3.0.0"

roles:
  - name: artis3n.tailscale
    src: https://github.com/artis3n/ansible-role-tailscale
    version: v5.0.1
